name: soundify
channels:
  - conda-forge
  - nvidia
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=pyhd8ed1ab_0
  - accelerate=1.11.0=pyhcf101f3_0
  - adwaita-icon-theme=49.0=unix_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h5541b7b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - audioread=3.0.1=py310hff52083_3
  - aws-c-auth=0.9.1=he9688bd_4
  - aws-c-cal=0.9.5=h346e085_1
  - aws-c-common=0.12.5=hb03c661_0
  - aws-c-compression=0.3.1=h7e655bb_7
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.6=hd09dbd4_1
  - aws-c-io=0.23.2=h6b699b9_1
  - aws-c-mqtt=0.13.3=hdd0c675_7
  - aws-c-s3=0.8.6=h2c9161e_6
  - aws-c-sdkutils=0.2.4=h7e655bb_2
  - aws-checksums=0.2.7=h7e655bb_3
  - aws-crt-cpp=0.35.0=h542abf0_1
  - aws-sdk-cpp=1.11.606=h522d481_5
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cryptography=46.0.3=py310hed992bd_0
  - cuda-cudart=12.1.105=hd3aeb46_0
  - cuda-cudart_linux-64=12.1.105=h59595ed_0
  - cuda-cupti=12.1.105=h59595ed_0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=hd3aeb46_0
  - cuda-nvtx=12.1.105=h59595ed_0
  - cuda-opencl=12.1.105=h59595ed_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.1=h1d6eff3_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - datasets=4.3.0=pyhcf101f3_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - diffusers=0.25.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - epoxy=1.5.10=hb03c661_2
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py310h9548a50_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - ghostscript=10.06.0=hecca717_0
  - giflib=5.2.2=hd590300_0
  - glib-tools=2.86.1=hf516916_1
  - glog=0.7.1=hbabe93e_0
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.42.1=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.2=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - graphviz=13.1.2=h87b6fe6_0
  - grpcio=1.73.1=py310h8f3b6d6_1
  - gtk3=3.24.43=h993cebd_6
  - gts=0.7.6=h977cf35_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hf-xet=1.2.0=py310hb823017_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - imagemagick=7.1.2_8=imagemagick_h6496278_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jbig=2.1=h7f98852_2003
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - kornia=0.7.0=pyhd8ed1ab_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.25.2=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=h99e40f8_3_cpu
  - libarrow-acero=22.0.0=h635bf11_3_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_3_cpu
  - libarrow-dataset=22.0.0=h635bf11_3_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_3_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp21.1=21.1.4=default_h99862b1_0
  - libclang13=21.1.4=default_h746c552_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.6.1.9=hd3aeb46_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.2.106=hd3aeb46_0
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.73.1=h3288cfb_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm21=21.1.4=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.1.105=hd3aeb46_0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=hd0c01bc_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=22.0.0=h7376487_3_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.08.12=h7b12aa8_1
  - librosa=0.11.0=pyhd8ed1ab_0
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libtasn1=4.20.0=ha30cf84_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libudev1=257.9=h085a93f_0
  - libunistring=0.9.10=h27cfd23_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.7.0=h439df22_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.3=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning=2.2.0.post0=pyhd8ed1ab_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.45.1=py310hee1c697_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.10.7=py310hff52083_0
  - matplotlib-base=3.10.7=py310hfde16b3_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2022.1.0=hc2b9512_224
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310h03d9f68_0
  - multidict=6.6.3=py310h89163eb_0
  - multiprocess=0.70.16=py310h139afa4_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.62.1=py310h3477d8a_0
  - numpy=1.26.4=py310hb13e2d6_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.3.3=py310h0158d43_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py310h80abafc_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pkg-config=0.29.2=h4bc722e_1009
  - platformdirs=4.5.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - proglog=0.1.10=pyhaa61c55_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.3.1=py310h89163eb_0
  - protobuf=6.31.1=py310ha36e12e_2
  - psutil=7.1.2=py310h139afa4_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - pyarrow=22.0.0=py310hff52083_0
  - pyarrow-core=22.0.0=py310h923f568_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py310h2007e60_1
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.12.1=pyhd8ed1ab_3
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.19=hd8ed1ab_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310hf3bd8b6_0
  - python_abi=3.10=8_cp310
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-lightning=2.5.5=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - regex=2025.10.23=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rich=13.9.4=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - s2n=1.5.27=h30d3c1c_1
  - safetensors=0.6.2=py310hdfeec95_1
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h3e344bc_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=1.0.0=py310hea6c23e_0
  - spirv-tools=2025.4=hb700be7_0
  - standard-aifc=3.13.0=py310hff52083_3
  - standard-sunau=3.13.0=py310hff52083_3
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h8d10470_0
  - tensorboard=2.15.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310hed992bd_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tokenizers=0.15.2=py310h320607d_0
  - torchaudio=2.1.2=py310_cu121
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchtriton=2.1.0=py310
  - torchvision=0.16.2=py310_cu121
  - tornado=6.5.2=py310h7c4b9e2_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.36.2=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!157.20191217=h7b6447c_0
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py310h139afa4_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alembic==1.17.1
      - autopage==0.5.2
      - bitsandbytes==0.43.1
      - blessed==1.22.0
      - cliff==4.11.0
      - cmaes==0.12.0
      - cmd2==2.7.0
      - colorlog==6.10.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gpustat==1.1.1
      - greenlet==3.2.4
      - hf-transfer==0.1.9
      - huggingface-hub==0.25.2
      - hydra-colorlog==1.2.0
      - hydra-optuna-sweeper==1.2.0
      - mako==1.3.10
      - nvidia-ml-py==13.580.82
      - nvitop==1.5.3
      - optuna==2.10.1
      - prettytable==3.16.0
      - pyperclip==1.11.0
      - python-dotenv==1.2.1
      - rich-argparse==1.7.2
      - rootutils==1.0.7
      - sentencepiece==0.2.0
      - smmap==5.0.2
      - sqlalchemy==2.0.44
      - stevedore==5.5.0
      - tomli==2.3.0
      - wcwidth==0.2.14
variables:
  PYTHONPATH: /workspace/images-that-sound
prefix: /workspace/miniconda/envs/soundify
